name: AppScan CodeSweep Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AppScan CodeSweep
        uses: IBM/AppScanCodeSweep-GitHubAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
