name: AppScan CodeSweep Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeSweep Scan
        uses: IBM/AppScanCodeSweep@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
